"""Add shared_with_user_id to Share model with named FK constraint

Revision ID: 14722babe515
Revises: 58f4e4198535
Create Date: 2025-05-11 15:01:38.324783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14722babe515'
down_revision = '58f4e4198535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_shared_with_user', 'users', ['shared_with_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shared_with_user', type_='foreignkey')
        batch_op.drop_column('shared_with_user_id')

    # ### end Alembic commands ###
