"""Add equipment fields to Dive table

Revision ID: 1f3dc88d3839
Revises: 7a7b264fee46
Create Date: 2025-05-07 18:28:29.678107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3dc88d3839'
down_revision = '7a7b264fee46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suit_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('suit_thickness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tank_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tank_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gas_mix', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('o2_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dives', schema=None) as batch_op:
        batch_op.drop_column('o2_percentage')
        batch_op.drop_column('gas_mix')
        batch_op.drop_column('tank_size')
        batch_op.drop_column('tank_type')
        batch_op.drop_column('weight')
        batch_op.drop_column('suit_thickness')
        batch_op.drop_column('suit_type')

    # ### end Alembic commands ###
